/* eslint-disable */
// @ts-nocheck
// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'id' : MessageId,
  'content' : string,
  'recipient' : UserId,
  'isImage' : boolean,
  'sender' : UserId,
  'timestamp' : Time,
}
export type MessageId = bigint;
export type PublicKey = string;
export type Time = bigint;
export type UserId = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<[Array<Uint8Array>], undefined>,
  '_caffeineStorageCreateCertificate' : ActorMethod<[string], _CaffeineStorageCreateCertificateResult>,
  '_caffeineStorageRefillCashier' : ActorMethod<[[] | [_CaffeineStorageRefillInformation]], _CaffeineStorageRefillResult>,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'getConversation' : ActorMethod<[UserId, UserId], Array<Message>>,
  'getPublicKey' : ActorMethod<[string], [] | [PublicKey]>,
  'listUsers' : ActorMethod<[], Array<string>>,
  'loginUser' : ActorMethod<[string, string], boolean>,
  'purgeExpiredMessages' : ActorMethod<[], bigint>,
  'registerUser' : ActorMethod<[string, string], undefined>,
  'sendMessage' : ActorMethod<[UserId, string, UserId, string, boolean], MessageId>,
  'storePublicKey' : ActorMethod<[string, string, PublicKey], undefined>,
  'unsendMessage' : ActorMethod<[MessageId, string, string], undefined>,
  'userExists' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
